# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
project 'Test'

target 'PhoneAuthSwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhoneAuthSwiftUI

pod 'IKEventSourceHirro'

end