source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/"}

ruby '3.1.2'


gem 'rails', '~> 6.1.7'

gem 'bootsnap', '>= 1.4.4'

gem 'sass-rails', '>= 6'


gem 'image_processing', '~> 1.2'


group :development, :test do

  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end
